// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserMicroserviceDAL.Context;

#nullable disable

namespace UserMicroserviceDAL.Migrations
{
    [DbContext(typeof(UserMicriserviceDBContext))]
    [Migration("20250114172716_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserMicroserviceDAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f9a39fb-6876-4dbf-9657-f1f29b519f4d"),
                            Email = "alice.smith@example.com",
                            FirstName = "Alic",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("e3a1976b-83e4-4f65-9b8f-67a5c317f8a7"),
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("0f5ea429-2e73-4a0b-93c3-f3b8b0eafb31"),
                            Email = "ethan.jones@example.com",
                            FirstName = "Ethan",
                            LastName = "Jones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
